//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionDiary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConstructionDiaryEntities : DbContext
    {
        public ConstructionDiaryEntities()
            : base("name=ConstructionDiaryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Clients> tbl_Clients { get; set; }
        public virtual DbSet<tbl_ContractorFinance> tbl_ContractorFinance { get; set; }
        public virtual DbSet<tbl_Finance> tbl_Finance { get; set; }
        public virtual DbSet<tbl_GeneralSetting> tbl_GeneralSetting { get; set; }
        public virtual DbSet<tbl_PackageType> tbl_PackageType { get; set; }
        public virtual DbSet<tbl_PaymentTransaction> tbl_PaymentTransaction { get; set; }
        public virtual DbSet<tbl_Persons> tbl_Persons { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_Sites> tbl_Sites { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
    
        public virtual ObjectResult<SP_GetPersonsList_Result> SP_GetPersonsList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetPersonsList_Result>("SP_GetPersonsList");
        }
    
        public virtual ObjectResult<SP_GetSiteDetailById_Result> SP_GetSiteDetailById(Nullable<System.Guid> siteId)
        {
            var siteIdParameter = siteId.HasValue ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetSiteDetailById_Result>("SP_GetSiteDetailById", siteIdParameter);
        }
    
        public virtual ObjectResult<SP_GetSitesList_Result> SP_GetSitesList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetSitesList_Result>("SP_GetSitesList");
        }
    
        public virtual ObjectResult<SP_GetTodayPartyFinance_Result> SP_GetTodayPartyFinance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetTodayPartyFinance_Result>("SP_GetTodayPartyFinance");
        }
    
        public virtual ObjectResult<SP_GetTodayPersonFinance_Result> SP_GetTodayPersonFinance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetTodayPersonFinance_Result>("SP_GetTodayPersonFinance");
        }
    }
}
