//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionDiary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BillSiteFinal
    {
        public System.Guid BillSiteFinalId { get; set; }
        public System.Guid BillId { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }
        public decimal Area { get; set; }
        public decimal Rate { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
    }
}
