//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionDiary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Pagar
    {
        public System.Guid PagarId { get; set; }
        public Nullable<System.Guid> PersonId { get; set; }
        public Nullable<System.Guid> GroupId { get; set; }
        public System.DateTime PagarStartDate { get; set; }
        public System.DateTime PagarEndDate { get; set; }
        public decimal PagarAmount { get; set; }
        public decimal TotalUpadAmount { get; set; }
        public decimal TotalOvertimeAmount { get; set; }
        public decimal AmountPay { get; set; }
        public decimal PrevPagarRemainingAmount { get; set; }
        public decimal RemainingAmount { get; set; }
        public Nullable<System.Guid> PagarPaidToPerson { get; set; }
        public string Remarks { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
