//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionDiary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MaterialPurchaseItems
    {
        public System.Guid MaterialPurchaseItemId { get; set; }
        public System.Guid MaterialPurchaseId { get; set; }
        public System.Guid MaterialTypeId { get; set; }
        public decimal Weight { get; set; }
        public decimal Rate { get; set; }
        public decimal Amount { get; set; }
    
        public virtual tbl_MaterialPurchase tbl_MaterialPurchase { get; set; }
        public virtual tbl_MaterialType tbl_MaterialType { get; set; }
    }
}
