//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionDiary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PagarPersonDetail
    {
        public System.Guid PagarPersonDetailId { get; set; }
        public System.Guid PagarId { get; set; }
        public Nullable<System.Guid> PersonId { get; set; }
        public Nullable<System.Guid> GroupId { get; set; }
        public Nullable<System.Guid> PagarPersonId { get; set; }
        public Nullable<decimal> TotalAttendanceDays { get; set; }
        public Nullable<decimal> TotalPagarAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
