//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionDiary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PersonAttendance
    {
        public System.Guid PersonAttendanceId { get; set; }
        public System.Guid AttendanceId { get; set; }
        public System.Guid PersonId { get; set; }
        public decimal AttendanceStatus { get; set; }
        public Nullable<System.Guid> SiteId { get; set; }
        public Nullable<int> PersonDailyRate { get; set; }
        public Nullable<decimal> PayableAmount { get; set; }
        public Nullable<int> WithdrawAmount { get; set; }
        public Nullable<int> OvertimeAmount { get; set; }
        public Nullable<decimal> TotalRokadiya { get; set; }
        public Nullable<int> PersonTypeId { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    }
}
