//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionDiary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Files
    {
        public System.Guid FileId { get; set; }
        public System.Guid ParentId { get; set; }
        public int FileCategory { get; set; }
        public string OriginalFileName { get; set; }
        public string EncryptFileName { get; set; }
    }
}
