//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionDiary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MobileAppsCategory
    {
        public long MobileAppCategoryId { get; set; }
        public long MobileAppId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryImage { get; set; }
    }
}
