//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionDiary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Persons
    {
        public System.Guid PersonId { get; set; }
        public string PersonFirstName { get; set; }
        public string PersonAddress { get; set; }
        public string MobileNo { get; set; }
        public string PersonPhoto { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> ClientId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DailyRate { get; set; }
        public Nullable<int> PersonTypeId { get; set; }
        public Nullable<bool> IsAttendancePerson { get; set; }
    
        public virtual tbl_PersonType tbl_PersonType { get; set; }
    }
}
