//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionDiary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BillSiteItem
    {
        public System.Guid BillSiteItemId { get; set; }
        public System.Guid BillId { get; set; }
        public string ItemCategory { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public decimal Amount { get; set; }
    }
}
