//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionDiary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Peticase
    {
        public System.Guid PeticashId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime SelectedDate { get; set; }
        public string CreditDebit { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.Guid> TableId { get; set; }
        public Nullable<int> AmountWhereUsed { get; set; }
        public string Remarks { get; set; }
        public System.Guid ClientId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
