//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionDiary.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConstructionDiary.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        public static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Attendance.
        /// </summary>
        public static string AddNewAttendance {
            get {
                return ResourceManager.GetString("AddNewAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Bill.
        /// </summary>
        public static string AddNewBill {
            get {
                return ResourceManager.GetString("AddNewBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Bill Item.
        /// </summary>
        public static string AddNewBillItem {
            get {
                return ResourceManager.GetString("AddNewBillItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Challan.
        /// </summary>
        public static string AddNewChallan {
            get {
                return ResourceManager.GetString("AddNewChallan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Client.
        /// </summary>
        public static string AddNewClient {
            get {
                return ResourceManager.GetString("AddNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Credit.
        /// </summary>
        public static string AddNewCredit {
            get {
                return ResourceManager.GetString("AddNewCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Customer.
        /// </summary>
        public static string AddNewCustomer {
            get {
                return ResourceManager.GetString("AddNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Estimate.
        /// </summary>
        public static string AddNewEstimate {
            get {
                return ResourceManager.GetString("AddNewEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Expense.
        /// </summary>
        public static string AddNewExpense {
            get {
                return ResourceManager.GetString("AddNewExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Finance.
        /// </summary>
        public static string AddNewFinance {
            get {
                return ResourceManager.GetString("AddNewFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Group.
        /// </summary>
        public static string AddNewGroup {
            get {
                return ResourceManager.GetString("AddNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Material.
        /// </summary>
        public static string AddNewMaterial {
            get {
                return ResourceManager.GetString("AddNewMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Material Type.
        /// </summary>
        public static string AddNewMaterialType {
            get {
                return ResourceManager.GetString("AddNewMaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Merchant.
        /// </summary>
        public static string AddNewMerchant {
            get {
                return ResourceManager.GetString("AddNewMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Merchant Payment.
        /// </summary>
        public static string AddNewMerchantPayment {
            get {
                return ResourceManager.GetString("AddNewMerchantPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Pagar.
        /// </summary>
        public static string AddNewPagar {
            get {
                return ResourceManager.GetString("AddNewPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Party.
        /// </summary>
        public static string AddNewParty {
            get {
                return ResourceManager.GetString("AddNewParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Person.
        /// </summary>
        public static string AddNewPerson {
            get {
                return ResourceManager.GetString("AddNewPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Peticash.
        /// </summary>
        public static string AddNewPeticash {
            get {
                return ResourceManager.GetString("AddNewPeticash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Purchase.
        /// </summary>
        public static string AddNewPurchase {
            get {
                return ResourceManager.GetString("AddNewPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Sale.
        /// </summary>
        public static string AddNewSale {
            get {
                return ResourceManager.GetString("AddNewSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Site.
        /// </summary>
        public static string AddNewSite {
            get {
                return ResourceManager.GetString("AddNewSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Truck.
        /// </summary>
        public static string AddNewTruck {
            get {
                return ResourceManager.GetString("AddNewTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Vehicle Owner.
        /// </summary>
        public static string AddNewVehicleOwner {
            get {
                return ResourceManager.GetString("AddNewVehicleOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Vehicle Rent.
        /// </summary>
        public static string AddNewVehicleRent {
            get {
                return ResourceManager.GetString("AddNewVehicleRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Amount.
        /// </summary>
        public static string AdjustmentAmount {
            get {
                return ResourceManager.GetString("AdjustmentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Amount.
        /// </summary>
        public static string AfterWithdrawLessAmt {
            get {
                return ResourceManager.GetString("AfterWithdrawLessAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Where Used.
        /// </summary>
        public static string AmountWhereUsed {
            get {
                return ResourceManager.GetString("AmountWhereUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance List.
        /// </summary>
        public static string AttendanceList {
            get {
                return ResourceManager.GetString("AttendanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baba Ramdev.
        /// </summary>
        public static string BabaRamdev {
            get {
                return ResourceManager.GetString("BabaRamdev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Amount.
        /// </summary>
        public static string BalanceAmount {
            get {
                return ResourceManager.GetString("BalanceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Date.
        /// </summary>
        public static string BillDate {
            get {
                return ResourceManager.GetString("BillDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill File.
        /// </summary>
        public static string BillFile {
            get {
                return ResourceManager.GetString("BillFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Item.
        /// </summary>
        public static string BillItem {
            get {
                return ResourceManager.GetString("BillItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Item List.
        /// </summary>
        public static string BillItemList {
            get {
                return ResourceManager.GetString("BillItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill List.
        /// </summary>
        public static string BillList {
            get {
                return ResourceManager.GetString("BillList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill No.
        /// </summary>
        public static string BillNo {
            get {
                return ResourceManager.GetString("BillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Type.
        /// </summary>
        public static string BillType {
            get {
                return ResourceManager.GetString("BillType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car No.
        /// </summary>
        public static string CarNo {
            get {
                return ResourceManager.GetString("CarNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGST.
        /// </summary>
        public static string CGST {
            get {
                return ResourceManager.GetString("CGST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challan.
        /// </summary>
        public static string Challan {
            get {
                return ResourceManager.GetString("Challan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challan Date.
        /// </summary>
        public static string ChallanDate {
            get {
                return ResourceManager.GetString("ChallanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challan List.
        /// </summary>
        public static string ChallanList {
            get {
                return ResourceManager.GetString("ChallanList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challan No.
        /// </summary>
        public static string ChallanNo {
            get {
                return ResourceManager.GetString("ChallanNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challan Photo.
        /// </summary>
        public static string ChallanPhotoFile {
            get {
                return ResourceManager.GetString("ChallanPhotoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        public static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque For.
        /// </summary>
        public static string ChequeFor {
            get {
                return ResourceManager.GetString("ChequeFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque No.
        /// </summary>
        public static string ChequeNo {
            get {
                return ResourceManager.GetString("ChequeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client List.
        /// </summary>
        public static string ClientList {
            get {
                return ResourceManager.GetString("ClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want your letter head in PDF ?.
        /// </summary>
        public static string ConfirmLetterHeadQuestion {
            get {
                return ResourceManager.GetString("ConfirmLetterHeadQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction.
        /// </summary>
        public static string Construction {
            get {
                return ResourceManager.GetString("Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit List.
        /// </summary>
        public static string CreditList {
            get {
                return ResourceManager.GetString("CreditList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentPassword.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers List.
        /// </summary>
        public static string CustomersList {
            get {
                return ResourceManager.GetString("CustomersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyRate.
        /// </summary>
        public static string DailyRate {
            get {
                return ResourceManager.GetString("DailyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        public static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit List.
        /// </summary>
        public static string DebitList {
            get {
                return ResourceManager.GetString("DebitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Bill.
        /// </summary>
        public static string EditBill {
            get {
                return ResourceManager.GetString("EditBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Challan.
        /// </summary>
        public static string EditChallan {
            get {
                return ResourceManager.GetString("EditChallan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Client.
        /// </summary>
        public static string EditClient {
            get {
                return ResourceManager.GetString("EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Merchant.
        /// </summary>
        public static string EditMerchant {
            get {
                return ResourceManager.GetString("EditMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Merchant Payment.
        /// </summary>
        public static string EditMerchantPayment {
            get {
                return ResourceManager.GetString("EditMerchantPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Vehicle Owner.
        /// </summary>
        public static string EditVehicleOwner {
            get {
                return ResourceManager.GetString("EditVehicleOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Vehicle Rent.
        /// </summary>
        public static string EditVehicleRent {
            get {
                return ResourceManager.GetString("EditVehicleRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id.
        /// </summary>
        public static string EmailId {
            get {
                return ResourceManager.GetString("EmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.
        /// </summary>
        public static string Estimate {
            get {
                return ResourceManager.GetString("Estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate Date.
        /// </summary>
        public static string EstimateDate {
            get {
                return ResourceManager.GetString("EstimateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate List.
        /// </summary>
        public static string EstimateList {
            get {
                return ResourceManager.GetString("EstimateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense File.
        /// </summary>
        public static string ExpenseFile {
            get {
                return ResourceManager.GetString("ExpenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense List.
        /// </summary>
        public static string ExpenseList {
            get {
                return ResourceManager.GetString("ExpenseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Type.
        /// </summary>
        public static string ExpenseType {
            get {
                return ResourceManager.GetString("ExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance List.
        /// </summary>
        public static string FinanceList {
            get {
                return ResourceManager.GetString("FinanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Name.
        /// </summary>
        public static string FirmName {
            get {
                return ResourceManager.GetString("FirmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Location.
        /// </summary>
        public static string FromLocation {
            get {
                return ResourceManager.GetString("FromLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Day.
        /// </summary>
        public static string FullDay {
            get {
                return ResourceManager.GetString("FullDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given/Taken By.
        /// </summary>
        public static string GivenTakenBy {
            get {
                return ResourceManager.GetString("GivenTakenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        public static string GrandTotal {
            get {
                return ResourceManager.GetString("GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Person.
        /// </summary>
        public static string GroupPerson {
            get {
                return ResourceManager.GetString("GroupPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST.
        /// </summary>
        public static string GST {
            get {
                return ResourceManager.GetString("GST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gujarati.
        /// </summary>
        public static string Gujarati {
            get {
                return ResourceManager.GetString("Gujarati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Day.
        /// </summary>
        public static string HalfDay {
            get {
                return ResourceManager.GetString("HalfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        public static string Hindi {
            get {
                return ResourceManager.GetString("Hindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Information.
        /// </summary>
        public static string ItemInfo {
            get {
                return ResourceManager.GetString("ItemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string ItemType {
            get {
                return ResourceManager.GetString("ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material List.
        /// </summary>
        public static string MaterialList {
            get {
                return ResourceManager.GetString("MaterialList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type.
        /// </summary>
        public static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type List.
        /// </summary>
        public static string MaterialTypeList {
            get {
                return ResourceManager.GetString("MaterialTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Name.
        /// </summary>
        public static string MerchantName {
            get {
                return ResourceManager.GetString("MerchantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Payment.
        /// </summary>
        public static string MerchantPayment {
            get {
                return ResourceManager.GetString("MerchantPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Payment List.
        /// </summary>
        public static string MerchantPaymentList {
            get {
                return ResourceManager.GetString("MerchantPaymentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchants.
        /// </summary>
        public static string Merchants {
            get {
                return ResourceManager.GetString("Merchants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchants List.
        /// </summary>
        public static string MerchantsList {
            get {
                return ResourceManager.GetString("MerchantsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old.
        /// </summary>
        public static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime.
        /// </summary>
        public static string Overtime {
            get {
                return ResourceManager.GetString("Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Type.
        /// </summary>
        public static string PackageType {
            get {
                return ResourceManager.GetString("PackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagar.
        /// </summary>
        public static string Pagar {
            get {
                return ResourceManager.GetString("Pagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagar Amount.
        /// </summary>
        public static string PagarAmount {
            get {
                return ResourceManager.GetString("PagarAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagar Date.
        /// </summary>
        public static string PagarDate {
            get {
                return ResourceManager.GetString("PagarDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagar List.
        /// </summary>
        public static string PagarList {
            get {
                return ResourceManager.GetString("PagarList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagar Pay Amount.
        /// </summary>
        public static string PagarPayAmount {
            get {
                return ResourceManager.GetString("PagarPayAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Access.
        /// </summary>
        public static string PageAccess {
            get {
                return ResourceManager.GetString("PageAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        public static string Party {
            get {
                return ResourceManager.GetString("Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party List.
        /// </summary>
        public static string PartyList {
            get {
                return ResourceManager.GetString("PartyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Name.
        /// </summary>
        public static string PartyName {
            get {
                return ResourceManager.GetString("PartyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Group.
        /// </summary>
        public static string PersonGroup {
            get {
                return ResourceManager.GetString("PersonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Group List.
        /// </summary>
        public static string PersonGroupList {
            get {
                return ResourceManager.GetString("PersonGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person List.
        /// </summary>
        public static string PersonList {
            get {
                return ResourceManager.GetString("PersonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonType.
        /// </summary>
        public static string PersonType {
            get {
                return ResourceManager.GetString("PersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peticash.
        /// </summary>
        public static string Peticash {
            get {
                return ResourceManager.GetString("Peticash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peticash List.
        /// </summary>
        public static string PeticashList {
            get {
                return ResourceManager.GetString("PeticashList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit/Debit.
        /// </summary>
        public static string PrevCreditDebit {
            get {
                return ResourceManager.GetString("PrevCreditDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Pagar Amount.
        /// </summary>
        public static string PreviousPagarAmount {
            get {
                return ResourceManager.GetString("PreviousPagarAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase List.
        /// </summary>
        public static string PurchaseList {
            get {
                return ResourceManager.GetString("PurchaseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Amount.
        /// </summary>
        public static string RemainingAmount {
            get {
                return ResourceManager.GetString("RemainingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rokadiya.
        /// </summary>
        public static string Rokadiya {
            get {
                return ResourceManager.GetString("Rokadiya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales List.
        /// </summary>
        public static string SalesList {
            get {
                return ResourceManager.GetString("SalesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGST.
        /// </summary>
        public static string SGST {
            get {
                return ResourceManager.GetString("SGST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Detail.
        /// </summary>
        public static string SiteDetail {
            get {
                return ResourceManager.GetString("SiteDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site List.
        /// </summary>
        public static string SiteList {
            get {
                return ResourceManager.GetString("SiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites.
        /// </summary>
        public static string Sites {
            get {
                return ResourceManager.GetString("Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        public static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Feet.
        /// </summary>
        public static string SquareFeet {
            get {
                return ResourceManager.GetString("SquareFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total Amount.
        /// </summary>
        public static string SubTotalAmount {
            get {
                return ResourceManager.GetString("SubTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to Delete ?.
        /// </summary>
        public static string SureWantToDelete {
            get {
                return ResourceManager.GetString("SureWantToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Location.
        /// </summary>
        public static string ToLocation {
            get {
                return ResourceManager.GetString("ToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Attendance Amount.
        /// </summary>
        public static string TotalAttendanceAmount {
            get {
                return ResourceManager.GetString("TotalAttendanceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Balance.
        /// </summary>
        public static string TotalBalance {
            get {
                return ResourceManager.GetString("TotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Clients.
        /// </summary>
        public static string TotalClient {
            get {
                return ResourceManager.GetString("TotalClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Credit.
        /// </summary>
        public static string TotalCredit {
            get {
                return ResourceManager.GetString("TotalCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Credit Amount (From Party).
        /// </summary>
        public static string TotalCreditAmount {
            get {
                return ResourceManager.GetString("TotalCreditAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Customers.
        /// </summary>
        public static string TotalCustomers {
            get {
                return ResourceManager.GetString("TotalCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Debit.
        /// </summary>
        public static string TotalDebit {
            get {
                return ResourceManager.GetString("TotalDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Debit Amount (Person).
        /// </summary>
        public static string TotalDebitAmount {
            get {
                return ResourceManager.GetString("TotalDebitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Expense Amount.
        /// </summary>
        public static string TotalExpenseAmount {
            get {
                return ResourceManager.GetString("TotalExpenseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Given Amount.
        /// </summary>
        public static string TotalGivenAmount {
            get {
                return ResourceManager.GetString("TotalGivenAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Material Amount.
        /// </summary>
        public static string TotalMaterialAmount {
            get {
                return ResourceManager.GetString("TotalMaterialAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Merchant.
        /// </summary>
        public static string TotalMerchant {
            get {
                return ResourceManager.GetString("TotalMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Overtime Amount.
        /// </summary>
        public static string TotalOvertimeAmount {
            get {
                return ResourceManager.GetString("TotalOvertimeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pagar.
        /// </summary>
        public static string TotalPagar {
            get {
                return ResourceManager.GetString("TotalPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Persons.
        /// </summary>
        public static string TotalPersons {
            get {
                return ResourceManager.GetString("TotalPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Present Days.
        /// </summary>
        public static string TotalPresentDays {
            get {
                return ResourceManager.GetString("TotalPresentDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Purchase.
        /// </summary>
        public static string TotalPurchase {
            get {
                return ResourceManager.GetString("TotalPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Remaining Amount.
        /// </summary>
        public static string TotalRemainingAmount {
            get {
                return ResourceManager.GetString("TotalRemainingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sale.
        /// </summary>
        public static string TotalSale {
            get {
                return ResourceManager.GetString("TotalSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sites.
        /// </summary>
        public static string TotalSite {
            get {
                return ResourceManager.GetString("TotalSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Taken Amount.
        /// </summary>
        public static string TotalTakenAmount {
            get {
                return ResourceManager.GetString("TotalTakenAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Withdraw Amount.
        /// </summary>
        public static string TotalWithdrawAmount {
            get {
                return ResourceManager.GetString("TotalWithdrawAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traders.
        /// </summary>
        public static string Traders {
            get {
                return ResourceManager.GetString("Traders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucks.
        /// </summary>
        public static string Trucks {
            get {
                return ResourceManager.GetString("Trucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucks List.
        /// </summary>
        public static string TrucksList {
            get {
                return ResourceManager.GetString("TrucksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        public static string UpdatedBy {
            get {
                return ResourceManager.GetString("UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Estimate.
        /// </summary>
        public static string UpdateEstimate {
            get {
                return ResourceManager.GetString("UpdateEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Person Detail.
        /// </summary>
        public static string UpdatePersonDetail {
            get {
                return ResourceManager.GetString("UpdatePersonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users List.
        /// </summary>
        public static string UsersList {
            get {
                return ResourceManager.GetString("UsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Number.
        /// </summary>
        public static string VehicleNumber {
            get {
                return ResourceManager.GetString("VehicleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Owner List.
        /// </summary>
        public static string VehicleOwnerList {
            get {
                return ResourceManager.GetString("VehicleOwnerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Owner Name.
        /// </summary>
        public static string VehicleOwnerName {
            get {
                return ResourceManager.GetString("VehicleOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Rent.
        /// </summary>
        public static string VehicleRent {
            get {
                return ResourceManager.GetString("VehicleRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Rent Date.
        /// </summary>
        public static string VehicleRentDate {
            get {
                return ResourceManager.GetString("VehicleRentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Rent List.
        /// </summary>
        public static string VehicleRentList {
            get {
                return ResourceManager.GetString("VehicleRentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight/Nos.
        /// </summary>
        public static string Weight_Nos {
            get {
                return ResourceManager.GetString("Weight_Nos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
    }
}
